version: '3'
services:
  sftp:
    volumes:
      - ./bootstrap-sftp.sh:/bootstrap-sftp.sh
      - ../packages/test-data/keys/ssh_client_rsa_key.pub:/etc/authorized_keys/user
      - ../packages/test-data:/data
  build_env:
    volumes:
      - ../:/source/cumulus
      - ../test-data/:/tmp/cumulus_unit_test_data
    ports:
      - "20:20"
      - "21:21"
      - 47400-47470:47400-47470
      - 3030:3030
      - 2222:2222
      - 4550-4586:4550-4586
      - 8080:8080
      - 9200:9200
